CREATE SCHEMA IF NOT EXISTS atlas_capital_intelligence;

CREATE TABLE atlas_capital_intelligence.portfolio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    portfolio_name VARCHAR(120) NOT NULL,
    base_currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    risk_profile VARCHAR(30) NOT NULL,
    cash_balance NUMERIC(18, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE atlas_capital_intelligence.portfolio_holding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL REFERENCES atlas_capital_intelligence.portfolio(id) ON DELETE CASCADE,
    ticker VARCHAR(10) NOT NULL,
    security_name VARCHAR(120) NOT NULL,
    asset_class VARCHAR(30) NOT NULL,
    quantity NUMERIC(18, 4) NOT NULL,
    average_cost NUMERIC(18, 4) NOT NULL,
    current_price NUMERIC(18, 4) NOT NULL,
    change_percent NUMERIC(7, 4) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO atlas_capital_intelligence.portfolio (id, user_id, portfolio_name, base_currency, risk_profile, cash_balance)
VALUES (1001, 501, 'Global Multi-Asset Portfolio', 'USD', 'Moderate', 128450.35);

INSERT INTO atlas_capital_intelligence.portfolio_holding (id, portfolio_id, ticker, security_name, asset_class, quantity, average_cost, current_price, change_percent)
VALUES
    (101, 1001, 'AAPL', 'Apple Inc.', 'Equity', 145.0000, 172.1500, 198.4200, 1.2400),
    (102, 1001, 'MSFT', 'Microsoft Corp.', 'Equity', 92.0000, 388.7600, 421.8800, 0.7600),
    (103, 1001, 'VTI', 'Vanguard Total Stock Market ETF', 'ETF', 210.0000, 243.1000, 271.3400, 0.3800),
    (104, 1001, 'BND', 'Vanguard Total Bond Market ETF', 'Bond', 530.0000, 71.4200, 73.1100, -0.1200),
    (105, 1001, 'GLD', 'SPDR Gold Shares', 'Alternative', 85.0000, 189.5500, 214.6700, 0.5700);

ALTER TABLE atlas_capital_intelligence.portfolio ALTER COLUMN id RESTART WITH 1002;
ALTER TABLE atlas_capital_intelligence.portfolio_holding ALTER COLUMN id RESTART WITH 106;
